// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `activity`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class UiActivity {
  final String id;
  final String deviceId;
  final String deviceName;
  final UiPlatform platform;
  final UiActivityKind kind;
  final UiActivityDirection direction;
  final UiActivityStatus status;
  final String title;
  final BigInt startedAt;
  final BigInt? endedAt;
  final BigInt? completedAt;
  final BigInt? disconnectedAt;
  final BigInt? fileCompletedAt;
  final String? failure;
  final String? url;
  final BigInt positionMillis;
  final String? retryOf;
  final String? sessionId;
  final BigInt revision;
  final String? filePath;
  final bool canRetry;

  const UiActivity({
    required this.id,
    required this.deviceId,
    required this.deviceName,
    required this.platform,
    required this.kind,
    required this.direction,
    required this.status,
    required this.title,
    required this.startedAt,
    this.endedAt,
    this.completedAt,
    this.disconnectedAt,
    this.fileCompletedAt,
    this.failure,
    this.url,
    required this.positionMillis,
    this.retryOf,
    this.sessionId,
    required this.revision,
    this.filePath,
    required this.canRetry,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      platform.hashCode ^
      kind.hashCode ^
      direction.hashCode ^
      status.hashCode ^
      title.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode ^
      completedAt.hashCode ^
      disconnectedAt.hashCode ^
      fileCompletedAt.hashCode ^
      failure.hashCode ^
      url.hashCode ^
      positionMillis.hashCode ^
      retryOf.hashCode ^
      sessionId.hashCode ^
      revision.hashCode ^
      filePath.hashCode ^
      canRetry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiActivity &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          platform == other.platform &&
          kind == other.kind &&
          direction == other.direction &&
          status == other.status &&
          title == other.title &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt &&
          completedAt == other.completedAt &&
          disconnectedAt == other.disconnectedAt &&
          fileCompletedAt == other.fileCompletedAt &&
          failure == other.failure &&
          url == other.url &&
          positionMillis == other.positionMillis &&
          retryOf == other.retryOf &&
          sessionId == other.sessionId &&
          revision == other.revision &&
          filePath == other.filePath &&
          canRetry == other.canRetry;
}

enum UiActivityDirection { outgoing, incoming, connection }

enum UiActivityEvent { changed }

enum UiActivityKind { url, youTube, file, localVideo, session }

class UiActivitySnapshot {
  final List<UiActivity> entries;
  final String? storageError;

  const UiActivitySnapshot({required this.entries, this.storageError});

  @override
  int get hashCode => entries.hashCode ^ storageError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiActivitySnapshot &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          storageError == other.storageError;
}

enum UiActivityStatus {
  active,
  delivered,
  completed,
  rejected,
  cancelled,
  failed,
  disconnected,
  interrupted,
}
