// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `new`, `new`, `new`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DevicesUiSubscription`, `HandoffUiSubscription`, `PairingUiSubscription`, `SettingsUiSubscription`, `TransferUiSubscription`, `UiSubscriptions`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

enum DevicesUiEvent {
  discoveryChanged,
  discoveryStatusChanged,
  trustedDevicesChanged,
  connectionsChanged,
  identityChanged,
}

enum HandoffUiEvent { outgoingChanged, incomingChanged }

enum PairingUiEvent { sessionsChanged }

enum SettingsUiEvent { directoryChanged, languageChanged, identityChanged }

enum TransferUiEvent { transfersChanged }
