// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`, `new`, `new`, `new`, `parse_device_id`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UiDiscoveryHandle>>
abstract class UiDiscoveryHandle implements RustOpaqueInterface {
  Future<void> advertise({required String host, required int port});

  Future<void> browseLocal();

  Future<bool> release();

  Future<void> useHandle();

  Future<void> useManualEndpoint({required String host, required int port});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UiFileTransferHandle>>
abstract class UiFileTransferHandle implements RustOpaqueInterface {
  Future<void> prepare({required String deviceId, required String source});

  Future<bool> release();

  Future<UiFileTransfer?> transfer();

  Future<void> useHandle();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UiHandoffHandle>>
abstract class UiHandoffHandle implements RustOpaqueInterface {
  Future<UiHandoff?> handoff();

  Future<void> prepareLocalVideo({
    required String deviceId,
    required String source,
    required BigInt playbackPositionMillis,
  });

  Future<void> prepareUrl({required String deviceId, required String url});

  Future<void> prepareYoutube({
    required String deviceId,
    required String url,
    required BigInt playbackPositionMillis,
  });

  Future<bool> release();

  Future<void> useHandle();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UiPairingHandle>>
abstract class UiPairingHandle implements RustOpaqueInterface {
  Future<void> approve();

  Future<void> prepareInitiator({required String host, required int port});

  Future<void> prepareReceiver();

  Future<void> reject();

  Future<bool> release();

  Future<UiPairingSession?> session();

  Future<void> useHandle();
}
