// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'activity.dart';
import 'error.dart';
import 'events.dart';
import 'handles.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_subscriptions`, `find_incoming_handoff_id`, `find_transfer_id`, `running_app`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UiBridge>>
abstract class UiBridge implements RustOpaqueInterface {
  Future<void> acceptTransfer({
    required String transferId,
    String? selectedDirectory,
  });

  Future<UiActivitySnapshot> activitySnapshot();

  Future<void> clearHistory();

  Future<void> connect({
    required String deviceId,
    required String host,
    required int port,
  });

  Future<UiDevicesSnapshot> devicesSnapshot();

  Future<void> disconnect({required String deviceId});

  Future<UiDiscoveryHandle> discoveryHandle({required String identifier});

  Future<UiFileTransferHandle> fileTransferHandle({required String identifier});

  Future<UiHandoffHandle> handoffHandle({required String identifier});

  Future<UiHandoffSnapshot> handoffSnapshot();

  Future<UiPairingHandle> pairingHandle({required String identifier});

  Future<UiPairingSnapshot> pairingSnapshot();

  Future<void> rejectTransfer({required String transferId});

  Future<void> removeActivity({required String activityId});

  Future<void> removeIncomingHandoff({required String handoffId});

  Future<void> removeTransfer({required String transferId});

  Future<void> removeTrustedDevice({required String deviceId});

  Future<void> retryActivity({required String activityId});

  Future<void> setDefaultTransferDirectory({required String directory});

  Future<void> setDisplayName({required String displayName});

  Future<void> setLanguage({required UiLanguage selectedLanguage});

  Future<UiSettingsSnapshot> settingsSnapshot();

  Future<void> shutdown();

  static Future<UiBridge> start({required String projectDirectory}) => RustLib
      .instance
      .api
      .crateApiManagerUiBridgeStart(projectDirectory: projectDirectory);

  Future<List<UiFileTransfer>> transfers();

  Stream<UiActivityEvent> watchActivity();

  Stream<DevicesUiEvent> watchDevices();

  Stream<HandoffUiEvent> watchHandoffs();

  Stream<PairingUiEvent> watchPairing();

  Stream<SettingsUiEvent> watchSettings();

  Stream<TransferUiEvent> watchTransfers();
}
