// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `candidate`, `connection`, `core_language`, `discovery_status`, `file_transfer_failure`, `file_transfer_state`, `file_transfer`, `handoff_failure`, `handoff_payload`, `handoff_state`, `handoff`, `incoming_handoff`, `language`, `local_device`, `pairing_failure`, `pairing_session`, `pairing_state`, `platform`, `text_direction`, `trusted_device`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class UiConnection {
  final String deviceId;
  final String displayName;
  final UiPlatform platform;
  final UiConnectionDirection direction;

  const UiConnection({
    required this.deviceId,
    required this.displayName,
    required this.platform,
    required this.direction,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      displayName.hashCode ^
      platform.hashCode ^
      direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiConnection &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          displayName == other.displayName &&
          platform == other.platform &&
          direction == other.direction;
}

enum UiConnectionDirection { incoming, outgoing, unknown }

class UiDevicesSnapshot {
  final UiLocalDevice localDevice;
  final UiDiscoveryStatus discoveryStatus;
  final List<UiDiscoveryCandidate> candidates;
  final List<UiTrustedDevice> trustedDevices;
  final List<UiConnection> connections;

  const UiDevicesSnapshot({
    required this.localDevice,
    required this.discoveryStatus,
    required this.candidates,
    required this.trustedDevices,
    required this.connections,
  });

  @override
  int get hashCode =>
      localDevice.hashCode ^
      discoveryStatus.hashCode ^
      candidates.hashCode ^
      trustedDevices.hashCode ^
      connections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiDevicesSnapshot &&
          runtimeType == other.runtimeType &&
          localDevice == other.localDevice &&
          discoveryStatus == other.discoveryStatus &&
          candidates == other.candidates &&
          trustedDevices == other.trustedDevices &&
          connections == other.connections;
}

class UiDiscoveryCandidate {
  final String id;
  final List<UiEndpoint> endpoints;
  final UiDiscoverySource source;

  const UiDiscoveryCandidate({
    required this.id,
    required this.endpoints,
    required this.source,
  });

  @override
  int get hashCode => id.hashCode ^ endpoints.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiDiscoveryCandidate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          endpoints == other.endpoints &&
          source == other.source;
}

enum UiDiscoverySource { local, manual, unknown }

enum UiDiscoveryStatus { idle, active, unavailable, unknown }

class UiEndpoint {
  final String host;
  final int port;

  const UiEndpoint({required this.host, required this.port});

  @override
  int get hashCode => host.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiEndpoint &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port;
}

class UiFileTransfer {
  final String id;
  final String peerDeviceId;
  final String fileName;
  final BigInt fileSize;
  final BigInt transferredBytes;
  final UiFileTransferDirection direction;
  final UiFileTransferState state;
  final UiFileTransferFailure? failure;
  final String? destination;

  const UiFileTransfer({
    required this.id,
    required this.peerDeviceId,
    required this.fileName,
    required this.fileSize,
    required this.transferredBytes,
    required this.direction,
    required this.state,
    this.failure,
    this.destination,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peerDeviceId.hashCode ^
      fileName.hashCode ^
      fileSize.hashCode ^
      transferredBytes.hashCode ^
      direction.hashCode ^
      state.hashCode ^
      failure.hashCode ^
      destination.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiFileTransfer &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peerDeviceId == other.peerDeviceId &&
          fileName == other.fileName &&
          fileSize == other.fileSize &&
          transferredBytes == other.transferredBytes &&
          direction == other.direction &&
          state == other.state &&
          failure == other.failure &&
          destination == other.destination;
}

enum UiFileTransferDirection { outgoing, incoming, unknown }

enum UiFileTransferFailure {
  notConnected,
  unsupported,
  invalid,
  busy,
  declined,
  timedOut,
  destinationConflict,
  integrity,
  fileSystem,
  transport,
  unknown,
}

enum UiFileTransferState {
  preparing,
  waitingForAcceptance,
  offered,
  transferring,
  verifying,
  completed,
  rejected,
  cancelled,
  failed,
  unknown,
}

class UiHandoff {
  final String id;
  final String destinationDeviceId;
  final UiHandoffPayload payload;
  final UiHandoffState state;
  final UiHandoffFailure? failure;
  final UiFileTransfer? transfer;

  const UiHandoff({
    required this.id,
    required this.destinationDeviceId,
    required this.payload,
    required this.state,
    this.failure,
    this.transfer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      destinationDeviceId.hashCode ^
      payload.hashCode ^
      state.hashCode ^
      failure.hashCode ^
      transfer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiHandoff &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          destinationDeviceId == other.destinationDeviceId &&
          payload == other.payload &&
          state == other.state &&
          failure == other.failure &&
          transfer == other.transfer;
}

enum UiHandoffFailure {
  notConnected,
  unsupported,
  invalid,
  busy,
  timedOut,
  transport,
  fileTransfer,
  unknown,
}

enum UiHandoffKind { url, youTube, localVideo, unknown }

class UiHandoffPayload {
  final UiHandoffKind kind;
  final String? url;
  final String? filePath;
  final BigInt playbackPositionMillis;
  final String? transferId;

  const UiHandoffPayload({
    required this.kind,
    this.url,
    this.filePath,
    required this.playbackPositionMillis,
    this.transferId,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      url.hashCode ^
      filePath.hashCode ^
      playbackPositionMillis.hashCode ^
      transferId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiHandoffPayload &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          url == other.url &&
          filePath == other.filePath &&
          playbackPositionMillis == other.playbackPositionMillis &&
          transferId == other.transferId;
}

class UiHandoffSnapshot {
  final List<UiHandoff> outgoing;
  final List<UiIncomingHandoff> incoming;

  const UiHandoffSnapshot({required this.outgoing, required this.incoming});

  @override
  int get hashCode => outgoing.hashCode ^ incoming.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiHandoffSnapshot &&
          runtimeType == other.runtimeType &&
          outgoing == other.outgoing &&
          incoming == other.incoming;
}

enum UiHandoffState { sending, delivered, rejected, cancelled, failed, unknown }

class UiIncomingHandoff {
  final String id;
  final String senderDeviceId;
  final UiHandoffPayload payload;

  const UiIncomingHandoff({
    required this.id,
    required this.senderDeviceId,
    required this.payload,
  });

  @override
  int get hashCode => id.hashCode ^ senderDeviceId.hashCode ^ payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiIncomingHandoff &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderDeviceId == other.senderDeviceId &&
          payload == other.payload;
}

enum UiLanguage { english, persian }

class UiLocalDevice {
  final String id;
  final String displayName;
  final UiPlatform platform;

  const UiLocalDevice({
    required this.id,
    required this.displayName,
    required this.platform,
  });

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode ^ platform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiLocalDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          platform == other.platform;
}

enum UiPairingFailure {
  securityUnavailable,
  connectionFailed,
  protocolMismatch,
  invalidPeer,
  timedOut,
  persistenceFailed,
  internal,
  unknown,
}

enum UiPairingRole { initiator, receiver, unknown }

class UiPairingSession {
  final String id;
  final UiPairingRole role;
  final UiPairingState state;
  final String? peerDeviceId;
  final String? peerDisplayName;
  final String? manualCode;
  final UiPairingFailure? failure;

  const UiPairingSession({
    required this.id,
    required this.role,
    required this.state,
    this.peerDeviceId,
    this.peerDisplayName,
    this.manualCode,
    this.failure,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      role.hashCode ^
      state.hashCode ^
      peerDeviceId.hashCode ^
      peerDisplayName.hashCode ^
      manualCode.hashCode ^
      failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiPairingSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          role == other.role &&
          state == other.state &&
          peerDeviceId == other.peerDeviceId &&
          peerDisplayName == other.peerDisplayName &&
          manualCode == other.manualCode &&
          failure == other.failure;
}

class UiPairingSnapshot {
  final UiEndpoint listeningEndpoint;
  final List<UiPairingSession> sessions;

  const UiPairingSnapshot({
    required this.listeningEndpoint,
    required this.sessions,
  });

  @override
  int get hashCode => listeningEndpoint.hashCode ^ sessions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiPairingSnapshot &&
          runtimeType == other.runtimeType &&
          listeningEndpoint == other.listeningEndpoint &&
          sessions == other.sessions;
}

enum UiPairingState {
  connecting,
  exchangingIdentity,
  awaitingVerification,
  persistingTrust,
  trusted,
  rejected,
  cancelled,
  expired,
  failed,
  unknown,
}

enum UiPlatform { windows, linux, macOs, android, ios, unknown }

class UiSettingsSnapshot {
  final String displayName;
  final String defaultTransferDirectory;
  final UiLanguage language;
  final UiTextDirection textDirection;

  const UiSettingsSnapshot({
    required this.displayName,
    required this.defaultTransferDirectory,
    required this.language,
    required this.textDirection,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^
      defaultTransferDirectory.hashCode ^
      language.hashCode ^
      textDirection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiSettingsSnapshot &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          defaultTransferDirectory == other.defaultTransferDirectory &&
          language == other.language &&
          textDirection == other.textDirection;
}

enum UiTextDirection { leftToRight, rightToLeft }

class UiTrustedDevice {
  final String id;
  final String displayName;
  final UiPlatform platform;

  const UiTrustedDevice({
    required this.id,
    required this.displayName,
    required this.platform,
  });

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode ^ platform.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiTrustedDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          platform == other.platform;
}
