import { ScrollView } from "std-widgets.slint";
import { Title, Label, Card, Button } from "../components.slint";
import { MaterialPalette } from "@material";

export component ErrorDialog inherits Card {
    in property <bool> rtl;
    in-out property <string> error-message;
    in property <string> close-text;
    callback dismiss-error-requested();

    TouchArea {}
    ScrollView {
        width: 100%; height: 100%; viewport-width: self.width;
        VerticalLayout {
            padding: 20px; spacing: 16px;
            Title { text: root.rtl ? "مشکلی پیش آمد" : "Something went wrong"; rtl: root.rtl; }
            Label { text: root.error-message; rtl: root.rtl; color: MaterialPalette.on-surface; }
            Button { text: root.close-text; clicked => { root.dismiss-error-requested(); } }
        }
    }
}
