import { ScrollView } from "std-widgets.slint";
import { Title, Label, Card, Button, SecondaryButton, AppTextField } from "../components.slint";

export component ReconnectDialog inherits Card {
    in property <bool> rtl;
    in-out property <string> reconnect-endpoint;
    callback device-action(string, string, string);
    in-out property <string> reconnect-device;
    callback close-reconnect-requested();

    TouchArea {}
    ScrollView {
        width: 100%; height: 100%; viewport-width: self.width;
        VerticalLayout {
            padding: 16px; spacing: 12px;
            Title { text: root.rtl ? "اتصال دوباره" : "Reconnect"; rtl: root.rtl; }
            Label { text: root.rtl ? "نشانی و درگاه اتصال دستگاه" : "Device IP address and connection port"; rtl: root.rtl; }
            AppTextField { text <=> root.reconnect-endpoint; label: "192.168.1.20:5300"; }
            Button { text: root.rtl ? "اتصال" : "Connect"; clicked => { root.device-action(root.reconnect-device, "connect", root.reconnect-endpoint); root.close-reconnect-requested(); } }
            SecondaryButton { text: root.rtl ? "بازگشت" : "Back"; clicked => { root.close-reconnect-requested(); } }
        }
    }
}
