name: continuehere_client
description: Continue activities on another trusted device.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  continuehere_bridge:
    path: rust_builder
  file_selector: ^1.1.0
  flutter_rust_bridge: 2.13.0
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  open_app_file: ^4.0.5
  path_provider: ^2.1.6
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
