import { MaterialScheme } from "@material";

export global AppTheme {
    in property <int> style;
    out property <color> accent: style == 1 ? #ff9c92 : style == 2 ? #91d7b4 : #c7a8ff;
    property <color> container: style == 1 ? #492c30 : style == 2 ? #223b32 : #392d50;
    property <color> background: #111117;
    property <color> low: #17171f;
    property <color> surface: #1e1e28;
    out property <color> sidebar: #15151d;
    out property <brush> backdrop: root.background;
    out property <MaterialScheme> scheme: {
        primary: root.accent,
        surfaceTint: root.accent,
        onPrimary: root.background,
        primaryContainer: root.container,
        onPrimaryContainer: #f4eaff,
        secondary: root.accent,
        onSecondary: root.background,
        secondaryContainer: root.container,
        onSecondaryContainer: #f4eaff,
        tertiary: root.accent,
        onTertiary: root.background,
        tertiaryContainer: root.container,
        onTertiaryContainer: #f4eaff,
        error: #ffb4ab,
        onError: #690005,
        errorContainer: #93000a,
        onErrorContainer: #ffdad6,
        background: root.background,
        onBackground: #eee8ed,
        surface: root.background,
        onSurface: #eee8ed,
        surfaceVariant: root.surface,
        onSurfaceVariant: #cec5ce,
        outline: #998e9b,
        outlineVariant: #504552,
        shadow: #000000,
        scrim: #000000,
        inverseSurface: #eee8ed,
        inverseOnSurface: #302b30,
        inversePrimary: root.container,
        primaryFixed: #f4eaff,
        onPrimaryFixed: root.background,
        primaryFixedDim: root.accent,
        onPrimaryFixedVariant: root.container,
        secondaryFixed: #f4eaff,
        onSecondaryFixed: root.background,
        secondaryFixedDim: root.accent,
        onSecondaryFixedVariant: root.container,
        tertiaryFixed: #f4eaff,
        onTertiaryFixed: root.background,
        tertiaryFixedDim: root.accent,
        onTertiaryFixedVariant: root.container,
        surfaceDim: root.background,
        surfaceBright: root.surface,
        surfaceContainerLowest: root.background,
        surfaceContainerLow: root.low,
        surfaceContainer: root.surface,
        surfaceContainerHigh: root.surface.brighter(8%),
        surfaceContainerHighest: root.surface.brighter(15%),
    };
}
