// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/events.dart';
import 'api/handles.dart';
import 'api/manager.dart';
import 'api/models.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiBridgePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridgePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiDiscoveryHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiFileTransferHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiHandoffHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandlePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UiPairingHandlePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandlePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  UiBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    dynamic raw,
  );

  @protected
  UiDiscoveryHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    dynamic raw,
  );

  @protected
  UiFileTransferHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    dynamic raw,
  );

  @protected
  UiHandoffHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    dynamic raw,
  );

  @protected
  UiPairingHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    dynamic raw,
  );

  @protected
  UiBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    dynamic raw,
  );

  @protected
  UiDiscoveryHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    dynamic raw,
  );

  @protected
  UiFileTransferHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    dynamic raw,
  );

  @protected
  UiHandoffHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    dynamic raw,
  );

  @protected
  UiPairingHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    dynamic raw,
  );

  @protected
  UiBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    dynamic raw,
  );

  @protected
  UiDiscoveryHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    dynamic raw,
  );

  @protected
  UiFileTransferHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    dynamic raw,
  );

  @protected
  UiHandoffHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    dynamic raw,
  );

  @protected
  UiPairingHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    dynamic raw,
  );

  @protected
  RustStreamSink<DevicesUiEvent> dco_decode_StreamSink_devices_ui_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<HandoffUiEvent> dco_decode_StreamSink_handoff_ui_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PairingUiEvent> dco_decode_StreamSink_pairing_ui_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SettingsUiEvent> dco_decode_StreamSink_settings_ui_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TransferUiEvent> dco_decode_StreamSink_transfer_ui_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  UiFileTransfer dco_decode_box_autoadd_ui_file_transfer(dynamic raw);

  @protected
  UiFileTransferFailure dco_decode_box_autoadd_ui_file_transfer_failure(
    dynamic raw,
  );

  @protected
  UiHandoff dco_decode_box_autoadd_ui_handoff(dynamic raw);

  @protected
  UiHandoffFailure dco_decode_box_autoadd_ui_handoff_failure(dynamic raw);

  @protected
  UiPairingFailure dco_decode_box_autoadd_ui_pairing_failure(dynamic raw);

  @protected
  UiPairingSession dco_decode_box_autoadd_ui_pairing_session(dynamic raw);

  @protected
  DevicesUiEvent dco_decode_devices_ui_event(dynamic raw);

  @protected
  HandoffUiEvent dco_decode_handoff_ui_event(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<UiConnection> dco_decode_list_ui_connection(dynamic raw);

  @protected
  List<UiDiscoveryCandidate> dco_decode_list_ui_discovery_candidate(
    dynamic raw,
  );

  @protected
  List<UiEndpoint> dco_decode_list_ui_endpoint(dynamic raw);

  @protected
  List<UiFileTransfer> dco_decode_list_ui_file_transfer(dynamic raw);

  @protected
  List<UiHandoff> dco_decode_list_ui_handoff(dynamic raw);

  @protected
  List<UiIncomingHandoff> dco_decode_list_ui_incoming_handoff(dynamic raw);

  @protected
  List<UiPairingSession> dco_decode_list_ui_pairing_session(dynamic raw);

  @protected
  List<UiTrustedDevice> dco_decode_list_ui_trusted_device(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  UiFileTransfer? dco_decode_opt_box_autoadd_ui_file_transfer(dynamic raw);

  @protected
  UiFileTransferFailure? dco_decode_opt_box_autoadd_ui_file_transfer_failure(
    dynamic raw,
  );

  @protected
  UiHandoff? dco_decode_opt_box_autoadd_ui_handoff(dynamic raw);

  @protected
  UiHandoffFailure? dco_decode_opt_box_autoadd_ui_handoff_failure(dynamic raw);

  @protected
  UiPairingFailure? dco_decode_opt_box_autoadd_ui_pairing_failure(dynamic raw);

  @protected
  UiPairingSession? dco_decode_opt_box_autoadd_ui_pairing_session(dynamic raw);

  @protected
  PairingUiEvent dco_decode_pairing_ui_event(dynamic raw);

  @protected
  SettingsUiEvent dco_decode_settings_ui_event(dynamic raw);

  @protected
  TransferUiEvent dco_decode_transfer_ui_event(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiBridgeError dco_decode_ui_bridge_error(dynamic raw);

  @protected
  UiBridgeErrorKind dco_decode_ui_bridge_error_kind(dynamic raw);

  @protected
  UiConnection dco_decode_ui_connection(dynamic raw);

  @protected
  UiConnectionDirection dco_decode_ui_connection_direction(dynamic raw);

  @protected
  UiDevicesSnapshot dco_decode_ui_devices_snapshot(dynamic raw);

  @protected
  UiDiscoveryCandidate dco_decode_ui_discovery_candidate(dynamic raw);

  @protected
  UiDiscoverySource dco_decode_ui_discovery_source(dynamic raw);

  @protected
  UiDiscoveryStatus dco_decode_ui_discovery_status(dynamic raw);

  @protected
  UiEndpoint dco_decode_ui_endpoint(dynamic raw);

  @protected
  UiFileTransfer dco_decode_ui_file_transfer(dynamic raw);

  @protected
  UiFileTransferDirection dco_decode_ui_file_transfer_direction(dynamic raw);

  @protected
  UiFileTransferFailure dco_decode_ui_file_transfer_failure(dynamic raw);

  @protected
  UiFileTransferState dco_decode_ui_file_transfer_state(dynamic raw);

  @protected
  UiHandoff dco_decode_ui_handoff(dynamic raw);

  @protected
  UiHandoffFailure dco_decode_ui_handoff_failure(dynamic raw);

  @protected
  UiHandoffKind dco_decode_ui_handoff_kind(dynamic raw);

  @protected
  UiHandoffPayload dco_decode_ui_handoff_payload(dynamic raw);

  @protected
  UiHandoffSnapshot dco_decode_ui_handoff_snapshot(dynamic raw);

  @protected
  UiHandoffState dco_decode_ui_handoff_state(dynamic raw);

  @protected
  UiIncomingHandoff dco_decode_ui_incoming_handoff(dynamic raw);

  @protected
  UiLanguage dco_decode_ui_language(dynamic raw);

  @protected
  UiLocalDevice dco_decode_ui_local_device(dynamic raw);

  @protected
  UiPairingFailure dco_decode_ui_pairing_failure(dynamic raw);

  @protected
  UiPairingRole dco_decode_ui_pairing_role(dynamic raw);

  @protected
  UiPairingSession dco_decode_ui_pairing_session(dynamic raw);

  @protected
  UiPairingSnapshot dco_decode_ui_pairing_snapshot(dynamic raw);

  @protected
  UiPairingState dco_decode_ui_pairing_state(dynamic raw);

  @protected
  UiPlatform dco_decode_ui_platform(dynamic raw);

  @protected
  UiSettingsSnapshot dco_decode_ui_settings_snapshot(dynamic raw);

  @protected
  UiTextDirection dco_decode_ui_text_direction(dynamic raw);

  @protected
  UiTrustedDevice dco_decode_ui_trusted_device(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  UiBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    SseDeserializer deserializer,
  );

  @protected
  UiDiscoveryHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiFileTransferHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiHandoffHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiPairingHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    SseDeserializer deserializer,
  );

  @protected
  UiDiscoveryHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiFileTransferHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiHandoffHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiPairingHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    SseDeserializer deserializer,
  );

  @protected
  UiDiscoveryHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiFileTransferHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiHandoffHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    SseDeserializer deserializer,
  );

  @protected
  UiPairingHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DevicesUiEvent> sse_decode_StreamSink_devices_ui_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<HandoffUiEvent> sse_decode_StreamSink_handoff_ui_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PairingUiEvent> sse_decode_StreamSink_pairing_ui_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SettingsUiEvent> sse_decode_StreamSink_settings_ui_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TransferUiEvent> sse_decode_StreamSink_transfer_ui_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  UiFileTransfer sse_decode_box_autoadd_ui_file_transfer(
    SseDeserializer deserializer,
  );

  @protected
  UiFileTransferFailure sse_decode_box_autoadd_ui_file_transfer_failure(
    SseDeserializer deserializer,
  );

  @protected
  UiHandoff sse_decode_box_autoadd_ui_handoff(SseDeserializer deserializer);

  @protected
  UiHandoffFailure sse_decode_box_autoadd_ui_handoff_failure(
    SseDeserializer deserializer,
  );

  @protected
  UiPairingFailure sse_decode_box_autoadd_ui_pairing_failure(
    SseDeserializer deserializer,
  );

  @protected
  UiPairingSession sse_decode_box_autoadd_ui_pairing_session(
    SseDeserializer deserializer,
  );

  @protected
  DevicesUiEvent sse_decode_devices_ui_event(SseDeserializer deserializer);

  @protected
  HandoffUiEvent sse_decode_handoff_ui_event(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<UiConnection> sse_decode_list_ui_connection(
    SseDeserializer deserializer,
  );

  @protected
  List<UiDiscoveryCandidate> sse_decode_list_ui_discovery_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<UiEndpoint> sse_decode_list_ui_endpoint(SseDeserializer deserializer);

  @protected
  List<UiFileTransfer> sse_decode_list_ui_file_transfer(
    SseDeserializer deserializer,
  );

  @protected
  List<UiHandoff> sse_decode_list_ui_handoff(SseDeserializer deserializer);

  @protected
  List<UiIncomingHandoff> sse_decode_list_ui_incoming_handoff(
    SseDeserializer deserializer,
  );

  @protected
  List<UiPairingSession> sse_decode_list_ui_pairing_session(
    SseDeserializer deserializer,
  );

  @protected
  List<UiTrustedDevice> sse_decode_list_ui_trusted_device(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  UiFileTransfer? sse_decode_opt_box_autoadd_ui_file_transfer(
    SseDeserializer deserializer,
  );

  @protected
  UiFileTransferFailure? sse_decode_opt_box_autoadd_ui_file_transfer_failure(
    SseDeserializer deserializer,
  );

  @protected
  UiHandoff? sse_decode_opt_box_autoadd_ui_handoff(
    SseDeserializer deserializer,
  );

  @protected
  UiHandoffFailure? sse_decode_opt_box_autoadd_ui_handoff_failure(
    SseDeserializer deserializer,
  );

  @protected
  UiPairingFailure? sse_decode_opt_box_autoadd_ui_pairing_failure(
    SseDeserializer deserializer,
  );

  @protected
  UiPairingSession? sse_decode_opt_box_autoadd_ui_pairing_session(
    SseDeserializer deserializer,
  );

  @protected
  PairingUiEvent sse_decode_pairing_ui_event(SseDeserializer deserializer);

  @protected
  SettingsUiEvent sse_decode_settings_ui_event(SseDeserializer deserializer);

  @protected
  TransferUiEvent sse_decode_transfer_ui_event(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiBridgeError sse_decode_ui_bridge_error(SseDeserializer deserializer);

  @protected
  UiBridgeErrorKind sse_decode_ui_bridge_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  UiConnection sse_decode_ui_connection(SseDeserializer deserializer);

  @protected
  UiConnectionDirection sse_decode_ui_connection_direction(
    SseDeserializer deserializer,
  );

  @protected
  UiDevicesSnapshot sse_decode_ui_devices_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  UiDiscoveryCandidate sse_decode_ui_discovery_candidate(
    SseDeserializer deserializer,
  );

  @protected
  UiDiscoverySource sse_decode_ui_discovery_source(
    SseDeserializer deserializer,
  );

  @protected
  UiDiscoveryStatus sse_decode_ui_discovery_status(
    SseDeserializer deserializer,
  );

  @protected
  UiEndpoint sse_decode_ui_endpoint(SseDeserializer deserializer);

  @protected
  UiFileTransfer sse_decode_ui_file_transfer(SseDeserializer deserializer);

  @protected
  UiFileTransferDirection sse_decode_ui_file_transfer_direction(
    SseDeserializer deserializer,
  );

  @protected
  UiFileTransferFailure sse_decode_ui_file_transfer_failure(
    SseDeserializer deserializer,
  );

  @protected
  UiFileTransferState sse_decode_ui_file_transfer_state(
    SseDeserializer deserializer,
  );

  @protected
  UiHandoff sse_decode_ui_handoff(SseDeserializer deserializer);

  @protected
  UiHandoffFailure sse_decode_ui_handoff_failure(SseDeserializer deserializer);

  @protected
  UiHandoffKind sse_decode_ui_handoff_kind(SseDeserializer deserializer);

  @protected
  UiHandoffPayload sse_decode_ui_handoff_payload(SseDeserializer deserializer);

  @protected
  UiHandoffSnapshot sse_decode_ui_handoff_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  UiHandoffState sse_decode_ui_handoff_state(SseDeserializer deserializer);

  @protected
  UiIncomingHandoff sse_decode_ui_incoming_handoff(
    SseDeserializer deserializer,
  );

  @protected
  UiLanguage sse_decode_ui_language(SseDeserializer deserializer);

  @protected
  UiLocalDevice sse_decode_ui_local_device(SseDeserializer deserializer);

  @protected
  UiPairingFailure sse_decode_ui_pairing_failure(SseDeserializer deserializer);

  @protected
  UiPairingRole sse_decode_ui_pairing_role(SseDeserializer deserializer);

  @protected
  UiPairingSession sse_decode_ui_pairing_session(SseDeserializer deserializer);

  @protected
  UiPairingSnapshot sse_decode_ui_pairing_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  UiPairingState sse_decode_ui_pairing_state(SseDeserializer deserializer);

  @protected
  UiPlatform sse_decode_ui_platform(SseDeserializer deserializer);

  @protected
  UiSettingsSnapshot sse_decode_ui_settings_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  UiTextDirection sse_decode_ui_text_direction(SseDeserializer deserializer);

  @protected
  UiTrustedDevice sse_decode_ui_trusted_device(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    UiBridge self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    UiDiscoveryHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    UiFileTransferHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    UiHandoffHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    UiPairingHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    UiBridge self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    UiDiscoveryHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    UiFileTransferHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    UiHandoffHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    UiPairingHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    UiBridge self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    UiDiscoveryHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    UiFileTransferHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    UiHandoffHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    UiPairingHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_devices_ui_event_Sse(
    RustStreamSink<DevicesUiEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_handoff_ui_event_Sse(
    RustStreamSink<HandoffUiEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_pairing_ui_event_Sse(
    RustStreamSink<PairingUiEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_settings_ui_event_Sse(
    RustStreamSink<SettingsUiEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transfer_ui_event_Sse(
    RustStreamSink<TransferUiEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ui_file_transfer(
    UiFileTransfer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_file_transfer_failure(
    UiFileTransferFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_handoff(
    UiHandoff self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_handoff_failure(
    UiHandoffFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_pairing_failure(
    UiPairingFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_pairing_session(
    UiPairingSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_devices_ui_event(
    DevicesUiEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_handoff_ui_event(
    HandoffUiEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_connection(
    List<UiConnection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_discovery_candidate(
    List<UiDiscoveryCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_endpoint(
    List<UiEndpoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_file_transfer(
    List<UiFileTransfer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_handoff(
    List<UiHandoff> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_incoming_handoff(
    List<UiIncomingHandoff> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_pairing_session(
    List<UiPairingSession> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_trusted_device(
    List<UiTrustedDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ui_file_transfer(
    UiFileTransfer? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_file_transfer_failure(
    UiFileTransferFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_handoff(
    UiHandoff? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_handoff_failure(
    UiHandoffFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_pairing_failure(
    UiPairingFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_pairing_session(
    UiPairingSession? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_ui_event(
    PairingUiEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_settings_ui_event(
    SettingsUiEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_ui_event(
    TransferUiEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_bridge_error(UiBridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_ui_bridge_error_kind(
    UiBridgeErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_connection(UiConnection self, SseSerializer serializer);

  @protected
  void sse_encode_ui_connection_direction(
    UiConnectionDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_devices_snapshot(
    UiDevicesSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_discovery_candidate(
    UiDiscoveryCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_discovery_source(
    UiDiscoverySource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_discovery_status(
    UiDiscoveryStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_endpoint(UiEndpoint self, SseSerializer serializer);

  @protected
  void sse_encode_ui_file_transfer(
    UiFileTransfer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_file_transfer_direction(
    UiFileTransferDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_file_transfer_failure(
    UiFileTransferFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_file_transfer_state(
    UiFileTransferState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_handoff(UiHandoff self, SseSerializer serializer);

  @protected
  void sse_encode_ui_handoff_failure(
    UiHandoffFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_handoff_kind(UiHandoffKind self, SseSerializer serializer);

  @protected
  void sse_encode_ui_handoff_payload(
    UiHandoffPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_handoff_snapshot(
    UiHandoffSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_handoff_state(
    UiHandoffState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_incoming_handoff(
    UiIncomingHandoff self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_language(UiLanguage self, SseSerializer serializer);

  @protected
  void sse_encode_ui_local_device(UiLocalDevice self, SseSerializer serializer);

  @protected
  void sse_encode_ui_pairing_failure(
    UiPairingFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_pairing_role(UiPairingRole self, SseSerializer serializer);

  @protected
  void sse_encode_ui_pairing_session(
    UiPairingSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_pairing_snapshot(
    UiPairingSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_pairing_state(
    UiPairingState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_platform(UiPlatform self, SseSerializer serializer);

  @protected
  void sse_encode_ui_settings_snapshot(
    UiSettingsSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_text_direction(
    UiTextDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_trusted_device(
    UiTrustedDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridgePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridgePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridgePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridge =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiBridgePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiDiscoveryHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiFileTransferHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiHandoffHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_continuehere_client_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUiPairingHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
